# infra/local/docker-compose.yaml

version: "3.8"

services:
  local-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: score
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - ./dbdata:/var/lib/mysql

  local-db-migrate:
    image: flyway/flyway:7
    environment:
      - FLYWAY_URL=jdbc:mysql://local-db/score
      - FLYWAY_USER=root
      - FLYWAY_PASSWORD=password
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
    command: migrate
    volumes:
      - ../../db/flyway.conf:/flyway/conf/flyway.conf
      - ../../db/migration:/flyway/sql
    depends_on:
      - local-db
